Required Fields in Liabilities and Income
swissfintechinnovations/ca-mortgage pull request #105
Opened 2022-10-28 12:13 UTC by simonbbaumgartner

In "Asset" the fields "assetType" and "amount" are required. in "liabilites" and "income", these two fields are not required. How come? We should mark these two fields in "liabilities" and "income" as required, too.

There is one more difference: asset has an additional field "assetProvider". Do we need/want this field for "liability" and "income" as well?

Anyway, why is there a different specification format for "liabilities" and "income" than for "asset"? "asset" is separately specified under "mortgage date types" whereas the other two are specified in the normal structure. Do we want to change it?

-> In this Pull request, only 1st point is addressed.

2022-10-28 12:54 UTC, rolfwagner requested changes
I would propose to discuss the alignment asset/liability/income in next mortgage meeting and afterwards correct it at once.

From my view, all changes suggested by Simon are valid (incl. make data types).

Simon, could you please make a proposal in this branch/PR for full alignment (incl. data types for liability, income as well)?

2022-10-31 12:58 UTC, olegkovalov approved these changes

2022-10-31 16:17 UTC, simonbbaumgartner commented
In "Asset" the fields "assetType" and "amount" are required. in "liabilites" and "income", these two fields are not required. How come? We should mark these two fields in "liabilities" and "income" as required, too. -> **added "required" for both**

There is one more difference: asset has an additional field "assetProvider". Do we need/want this field for "liability" and "income" as well? -> **added this additional information fields.**

Anyway, why is there a different specification format for "liabilities" and "income" than for "asset"? "asset" is separately specified under "mortgage date types" whereas the other two are specified in the normal structure. Do we want to change it? -> **didn't change. It has a reason for different approach. Asset is used in different objects and should therefore be specified in a separate structure. that's good.**

2022-11-03 20:46 UTC, rolfwagner approved these changes

2022-11-03 20:46 UTC, merged