New Setup: Additional Properties
swissfintechinnovations/ca-mortgage pull request #84
Opened 2022-09-20 07:04 UTC by simonbbaumgartner

The income and costs of other properties held by the applicant need to be considered in the affordability calculation. So, the FI needs to know the situation of additional properties.

In the object "financialSituation" we would like to have a new object "additionalProperties" as a list/array: description: Information about additional property required fields: valueAdditionalProperty, propertyTypeAdditionalProperty

In the new object "additionalProperties" are the following fields:

streetNameAdditionalProperty
description: Street name of the additional property type: String, max. 70

valueAdditionalProperty
description Value of the additional property
type: see Amount

propertyTypeAdditionalProperty
description: The type of the additional property
type: string, enum: [single_family_house, condominium, vacation_house, vacation_condominium, agricultural_farm, 2or3_family_house, multi_family_house, residential_building_plot, building_plot_other, mixed_property, commercial_condominium, office_building, industrial_building, special_object]

2022-09-29 14:30 UTC, simonbbaumgartner commented
should be done

2022-10-04 11:49 UTC, stjosh approved these changes
Looks good to me

2022-10-28 12:09 UTC, rolfwagner requested changes
Does it make sense to add street name of the additional property only without, Plz, city, (country)? -->e.g. structuredAddress

Other idea is to declare it as an asset (asset type, amount)?

2022-10-28 16:00 UTC, rolfwagner approved these changes

2022-10-28 16:00 UTC, merged