New Setup: Amount for Asset Type Insurances
swissfintechinnovations/ca-mortgage pull request #87
Opened 2022-09-20 07:49 UTC by simonbbaumgartner

For insurances (Asset Typ enum: life_insurance_3a, life_insurance_3b) two different types of amount are interesting for the FI:

surrender value / Rückkaufswert
insurance sum / Versicherungssumme
Both of them will be entered in the core banking system. So we would like to transfer both amounts. Is it possible to add a new field in the object "Asset": name: insurance sum
description: The amount of the sum insured
Type: see Amount

So, we can send the surrender value in the current field "amount" and send the insurance sum in the new field.

2022-10-04 11:51 UTC, stjosh requested changes

2022-10-04 11:51 UTC, stjosh commented on mortgageAPI.yaml
> +        insurance sum:
That's not a valid YAML key. Should be `insuranceSum`

2022-10-10 10:05 UTC, simonbbaumgartner commented
change to "insuranceSum"

2022-10-28 12:24 UTC, rolfwagner approved these changes
ok, minor change

2022-10-28 12:24 UTC, merged