New Endpoint for full data transfer
swissfintechinnovations/ca-mortgage pull request #96
Opened 2022-10-25 06:45 UTC by stjosh

See https://github.com/swissfintechinnovations/ca-mortgage/issues/49

2022-10-28 12:41 UTC, rolfwagner requested changes
Looks ok, at first glance.
Please rename  /cases to /mortage-cases*

2022-10-28 13:19 UTC, stjosh commented
@rolfwagner Thanks for your feedback - I have renamed the enpoints.

2022-10-28 14:13 UTC, rolfwagner commented
@olegkovalov Ok for MP? Scope rls 3. We will discuss it at the next mortgage meeting.

2022-11-02 09:41 UTC, olegkovalov approved these changes

2022-11-02 14:00 UTC, stjosh commented on mortgageAPI.yaml
> +      description: List of mortgage cases for the authenticated contiext including the corresponding properties, sorted by caseId
Many thanks, good catch. I have just fixed it.

2022-11-02 14:01 UTC, stjosh commented
@rolfwagner So I guess we're ready to merge? 😃

2022-11-03 20:50 UTC, rolfwagner approved these changes
ok

2022-11-03 20:52 UTC, merged